import { NotificationStatus } from '../../shared/types';

/**
 * A notification delivered to a single recipient. Lifecycle states are
 * PENDING -> SENT -> READ -> ARCHIVED. A notification is created PENDING with a
 * null `readAt`; `readAt` is only set when the notification is marked read (at
 * which point `status` becomes READ).
 *
 * `relatedEntityType` and `relatedEntityId` are either both null (a standalone
 * notification) or both non-null (a notification about a specific entity); they
 * are never mixed. `id` and `createdAt` are generated by the repository and are
 * never caller-supplied.
 */
export interface Notification {
  id: string;
  recipientId: string;
  type: string;
  title: string;
  message: string;
  relatedEntityType: string | null;
  relatedEntityId: string | null;
  status: NotificationStatus;
  createdAt: Date;
  readAt: Date | null;
}

/**
 * The caller-supplied payload for creating a notification. `id` and `createdAt`
 * are generated by the repository; `status` defaults to PENDING and `readAt` is
 * always null at creation time.
 */
export interface CreateNotificationInput {
  recipientId: string;
  type: string;
  title: string;
  message: string;
  relatedEntityType?: string | null;
  relatedEntityId?: string | null;
  status?: NotificationStatus;
}
