import { NotificationStatus } from '../../shared/types';

/**
 * A notification delivered to an employee. `id` and `createdAt` are generated
 * by the repository; `status` defaults to PENDING and `readAt` is null until
 * the notification is marked read via `markRead`.
 */
export interface Notification {
  id: string;
  recipientId: string;
  type: string;
  title: string;
  message: string;
  relatedEntityType: string | null;
  relatedEntityId: string | null;
  status: NotificationStatus;
  createdAt: Date;
  readAt: Date | null;
}

/**
 * The caller-supplied payload for creating a notification. `id`, `createdAt`,
 * `status` and `readAt` are generated by the repository; `relatedEntityType`
 * and `relatedEntityId` must be provided together (or both omitted) because
 * they identify the same related entity.
 */
export interface CreateNotificationInput {
  recipientId: string;
  type: string;
  title: string;
  message: string;
  relatedEntityType?: string | null;
  relatedEntityId?: string | null;
  status?: NotificationStatus;
}
