import { AuditAction } from '../../shared/types';

/**
 * An immutable audit-log entry. AuditLog has no lifecycle states and is only
 * ever created via `record`; there are no update or delete transitions.
 */
export interface AuditLog {
  id: string;
  entityType: string;
  entityId: string;
  action: AuditAction;
  oldValues: Record<string, any> | null;
  newValues: Record<string, any> | null;
  performedBy: string | null;
  performedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * The caller-supplied payload for recording an audit entry. `id`, `createdAt`
 * and `updatedAt` are generated by the repository; `performedAt` defaults to
 * the time of recording when omitted.
 */
export interface AuditLogInput {
  entityType: string;
  entityId: string;
  action: AuditAction;
  oldValues?: Record<string, any> | null;
  newValues?: Record<string, any> | null;
  performedBy?: string | null;
  performedAt?: Date;
}
