import { EmploymentStatus } from '../../shared/types';

/**
 * An employee record. `id`, `createdAt` and `updatedAt` are generated by the
 * repository; `deletedAt` is null until `softDelete` and `terminationDate` is
 * null while the employee is not terminated.
 */
export interface Employee {
  id: string;
  employeeNumber: string;
  firstName: string;
  lastName: string;
  email: string;
  managerId: string | null;
  department: string | null;
  hireDate: Date;
  terminationDate: Date | null;
  employmentStatus: EmploymentStatus;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
}

/**
 * The caller-supplied payload for creating an employee. `id`, `createdAt`,
 * `updatedAt`, `deletedAt` and (unless terminated) `terminationDate` are
 * generated by the repository.
 */
export interface CreateEmployeeInput {
  employeeNumber: string;
  firstName: string;
  lastName: string;
  email: string;
  managerId?: string | null;
  department?: string | null;
  hireDate: Date;
  terminationDate?: Date | null;
  employmentStatus?: EmploymentStatus;
}

/**
 * The caller-supplied changes for an update. Only the supplied fields are
 * persisted; `id`, `createdAt` and `updatedAt` are never caller-supplied.
 */
export interface UpdateEmployeeInput {
  employeeNumber?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  managerId?: string | null;
  department?: string | null;
  hireDate?: Date;
  terminationDate?: Date | null;
  employmentStatus?: EmploymentStatus;
}
