import { LeaveType } from '../../shared/types';

/**
 * Defines the rules and entitlement configuration for a leave type. `id`,
 * `createdAt` and `updatedAt` are generated by the repository and never
 * caller-supplied. Lifecycle state is expressed via the boolean `isActive`
 * (ACTIVE / INACTIVE); there is no soft delete for policies.
 */
export interface LeavePolicy {
  id: string;
  policyName: string;
  leaveType: LeaveType;
  entitlementDays: number;
  accrualRate: number | undefined;
  maxAccumulation: number | undefined;
  minimumNoticeDays: number | undefined;
  requiresManagerApproval: boolean;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * The caller-supplied payload for creating a policy. Optional numeric fields
 * map to NULL when omitted; `requiresManagerApproval` defaults to false and
 * `isActive` defaults to true.
 */
export interface CreateLeavePolicyInput {
  policyName: string;
  leaveType: LeaveType;
  entitlementDays: number;
  accrualRate?: number;
  maxAccumulation?: number;
  minimumNoticeDays?: number;
  requiresManagerApproval?: boolean;
  isActive?: boolean;
}

/**
 * The caller-supplied changes for an update. Only the supplied fields are
 * persisted; `id`, `createdAt` and `updatedAt` are never caller-supplied.
 */
export interface UpdateLeavePolicyInput {
  policyName?: string;
  leaveType?: LeaveType;
  entitlementDays?: number;
  accrualRate?: number;
  maxAccumulation?: number;
  minimumNoticeDays?: number;
  requiresManagerApproval?: boolean;
  isActive?: boolean;
}
