export type LeaveType = 'ANNUAL' | 'SICK' | 'MATERNITY' | 'PATERNITY' | 'UNPAID' | 'OTHER';
export type LeaveStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
export type NotificationType = 'LEAVE_REQUEST_CREATED' | 'LEAVE_REQUEST_APPROVED' | 'LEAVE_REQUEST_REJECTED' | 'LEAVE_REQUEST_CANCELLED' | 'LEAVE_BALANCE_LOW' | 'LEAVE_BALANCE_EXPIRING';
export type AuditAction = 'CREATE' | 'UPDATE' | 'DELETE';
export type EntityType = 'LEAVE_REQUEST' | 'LEAVE_BALANCE' | 'LEAVE_POLICY' | 'EMPLOYEE' | 'NOTIFICATION';
