export enum NotificationType {
  LEAVE_REQUEST_CREATED = 'LEAVE_REQUEST_CREATED',
  LEAVE_REQUEST_APPROVED = 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_REJECTED = 'LEAVE_REQUEST_REJECTED',
  LEAVE_REQUEST_CANCELLED = 'LEAVE_REQUEST_CANCELLED',
  LEAVE_BALANCE_LOW = 'LEAVE_BALANCE_LOW',
  LEAVE_BALANCE_EXPIRING = 'LEAVE_BALANCE_EXPIRING'
}
