import { LeaveStatus, LeaveTypeCode } from '../../shared/types';

/**
 * A single application by an employee for a span of leave of one type, moving
 * through an approval lifecycle (DRAFT -> SUBMITTED -> APPROVED/REJECTED, or
 * CANCELLED). The canonical shape is a cross-module data contract and must not
 * gain, lose, or rename any field without a matching repository/schema change.
 */
export interface LeaveRequest {
  id: string;
  employeeId: string;
  leaveTypeCode: LeaveTypeCode;
  startDate: Date;
  endDate: Date;
  requestedDays: number;
  reason: string | null;
  status: LeaveStatus;
  approverId: string | null;
  approvalComment: string | null;
  submittedAt: Date | null;
  decidedAt: Date | null;
  cancelledBy: string | null;
  cancelledAt: Date | null;
  /**
   * Null on ordinary requests; on a reversal instance it holds the id of the original
   * request it reverses. Set once at insert and immutable thereafter.
   */
  reversesRequestId: string | null;
}

/** Full set of persisted fields, leaving `id` to be generated by the repository. */
export type CreateLeaveRequestInput = Omit<LeaveRequest, 'id'>;
