import { LeaveType, LeaveStatus } from '../../shared/types';

/**
 * A leave request. `id`, `createdAt` and `updatedAt` are generated by the
 * repository; a request is created as PENDING immediately (`status` is never
 * caller-supplied on create). `approvedBy` and `approvedAt` are null until the
 * request is approved or rejected, and `reason` is undefined when the
 * applicant supplied none.
 */
export interface LeaveRequest {
  id: string;
  employeeId: string;
  leaveType: LeaveType;
  startDate: Date;
  endDate: Date;
  reason: string | undefined;
  status: LeaveStatus;
  approvedBy: string | null;
  approvedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * The caller-supplied changes for a status transition (approve / reject /
 * cancel). Only the supplied fields are persisted; `id`, `createdAt` and
 * `updatedAt` are never caller-supplied.
 */
export interface UpdateLeaveRequestInput {
  status?: LeaveStatus;
  approvedBy?: string | null;
  approvedAt?: Date | null;
}
